name: Build Docker Rewards - Alpine

on:
  # 1. Gatilho para execução manual a partir da aba "Actions"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 🐳 Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 🔧 Build da imagem
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask:latest .

      - name: 🚀 Push para o Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flask:latest
